-- ============================================
-- HRGENIUS DATABASE SCHEMA
-- Security, Organization, Recruitment
-- and Onboarding Tables
-- ============================================


-- ============================================
-- 1. USERS
-- ============================================

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMP,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_active CHECK (is_active IN (0, 1))
);


-- ============================================
-- 2. ROLES
-- ============================================

CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(50) NOT NULL,
    description VARCHAR2(255),

    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uq_roles_name UNIQUE (name)
);


-- ============================================
-- 3. USER_ROLES
-- ============================================

CREATE TABLE user_roles (
    user_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,

    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
        REFERENCES users(id),

    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id)
        REFERENCES roles(id)
);


-- ============================================
-- 4. DEPARTMENTS
-- ============================================

CREATE TABLE departments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_departments PRIMARY KEY (id),
    CONSTRAINT uq_departments_name UNIQUE (name),
    CONSTRAINT chk_departments_active CHECK (is_active IN (0, 1))
);


-- ============================================
-- 5. DESIGNATIONS
-- ============================================

CREATE TABLE designations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_designations PRIMARY KEY (id),
    CONSTRAINT uq_designations_name UNIQUE (name),
    CONSTRAINT chk_designations_active CHECK (is_active IN (0, 1))
);


-- ============================================
-- 6. EMPLOYEES
-- ============================================

CREATE TABLE employees (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER NOT NULL,
    employee_code VARCHAR2(50) NOT NULL,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100),
    phone VARCHAR2(20),
    date_of_birth DATE,
    gender VARCHAR2(20),
    joining_date DATE NOT NULL,
    employment_status VARCHAR2(30) DEFAULT 'ONBOARDING' NOT NULL,
    department_id NUMBER NOT NULL,
    designation_id NUMBER NOT NULL,
    manager_id NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_employees PRIMARY KEY (id),

    CONSTRAINT uq_employees_user UNIQUE (user_id),
    CONSTRAINT uq_employees_code UNIQUE (employee_code),

    CONSTRAINT fk_employees_user
        FOREIGN KEY (user_id)
        REFERENCES users(id),

    CONSTRAINT fk_employees_department
        FOREIGN KEY (department_id)
        REFERENCES departments(id),

    CONSTRAINT fk_employees_designation
        FOREIGN KEY (designation_id)
        REFERENCES designations(id),

    CONSTRAINT fk_employees_manager
        FOREIGN KEY (manager_id)
        REFERENCES employees(id),

    CONSTRAINT chk_employees_status
        CHECK (
            employment_status IN (
                'ONBOARDING',
                'ACTIVE',
                'ON_LEAVE',
                'NOTICE_PERIOD',
                'RESIGNED',
                'TERMINATED'
            )
        )
);


-- ============================================
-- 7. JOB_OPENINGS
-- ============================================

CREATE TABLE job_openings (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR2(150) NOT NULL,
    description CLOB,
    department_id NUMBER NOT NULL,
    designation_id NUMBER NOT NULL,
    employment_type VARCHAR2(30) NOT NULL,
    location VARCHAR2(150),
    openings_count NUMBER DEFAULT 1 NOT NULL,
    status VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_job_openings PRIMARY KEY (id),

    CONSTRAINT fk_job_openings_department
        FOREIGN KEY (department_id)
        REFERENCES departments(id),

    CONSTRAINT fk_job_openings_designation
        FOREIGN KEY (designation_id)
        REFERENCES designations(id),

    CONSTRAINT chk_job_openings_count
        CHECK (openings_count > 0),

    CONSTRAINT chk_job_openings_status
        CHECK (
            status IN (
                'DRAFT',
                'OPEN',
                'CLOSED',
                'CANCELLED'
            )
        )
);


-- ============================================
-- 8. CANDIDATES
-- ============================================

CREATE TABLE candidates (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    job_opening_id NUMBER NOT NULL,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100),
    email VARCHAR2(150) NOT NULL,
    phone VARCHAR2(20),
    resume_url VARCHAR2(500),
    experience_years NUMBER(5,2) DEFAULT 0 NOT NULL,
    status VARCHAR2(30) DEFAULT 'APPLIED' NOT NULL,
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_candidates PRIMARY KEY (id),

    CONSTRAINT fk_candidates_job
        FOREIGN KEY (job_opening_id)
        REFERENCES job_openings(id),

    CONSTRAINT chk_candidates_experience
        CHECK (experience_years >= 0),

    CONSTRAINT chk_candidates_status
        CHECK (
            status IN (
                'APPLIED',
                'SCREENING',
                'SHORTLISTED',
                'INTERVIEW',
                'SELECTED',
                'REJECTED'
            )
        )
);


-- ============================================
-- 9. INTERVIEWS
-- ============================================

CREATE TABLE interviews (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    candidate_id NUMBER NOT NULL,
    interviewer_id NUMBER NOT NULL,
    scheduled_at TIMESTAMP NOT NULL,
    interview_mode VARCHAR2(20) NOT NULL,
    status VARCHAR2(20) DEFAULT 'SCHEDULED' NOT NULL,
    interview_result VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    feedback CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_interviews PRIMARY KEY (id),

    CONSTRAINT fk_interviews_candidate
        FOREIGN KEY (candidate_id)
        REFERENCES candidates(id),

    CONSTRAINT fk_interviews_interviewer
        FOREIGN KEY (interviewer_id)
        REFERENCES employees(id),

    CONSTRAINT chk_interviews_mode
        CHECK (
            interview_mode IN (
                'ONLINE',
                'OFFLINE',
                'PHONE'
            )
        ),

    CONSTRAINT chk_interviews_status
        CHECK (
            status IN (
                'SCHEDULED',
                'COMPLETED',
                'CANCELLED'
            )
        ),

    CONSTRAINT chk_interviews_result
        CHECK (
            interview_result IN (
                'PENDING',
                'PASS',
                'FAIL'
            )
        )
);


-- ============================================
-- 10. ONBOARDING_TASKS
-- ============================================

CREATE TABLE onboarding_tasks (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employee_id NUMBER NOT NULL,
    task_name VARCHAR2(150) NOT NULL,
    description VARCHAR2(500),
    due_date DATE,
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_onboarding_tasks PRIMARY KEY (id),

    CONSTRAINT fk_onboarding_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(id),

    CONSTRAINT chk_onboarding_status
        CHECK (
            status IN (
                'PENDING',
                'IN_PROGRESS',
                'COMPLETED'
            )
        )
);

CREATE TABLE attendance (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employee_id NUMBER NOT NULL,
    attendance_date DATE NOT NULL,
    check_in TIMESTAMP,
    check_out TIMESTAMP,
    status VARCHAR2(20) DEFAULT 'PRESENT' NOT NULL,
    remarks VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_attendance PRIMARY KEY (id),

    CONSTRAINT fk_attendance_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(id),

    CONSTRAINT uq_attendance_employee_date
        UNIQUE (employee_id, attendance_date),

    CONSTRAINT chk_attendance_status
        CHECK (
            status IN (
                'PRESENT',
                'ABSENT',
                'HALF_DAY',
                'ON_LEAVE'
            )
        )
);

CREATE TABLE leave_types (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(50) NOT NULL,
    description VARCHAR2(255),
    default_days NUMBER(5,2) DEFAULT 0 NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_leave_types PRIMARY KEY (id),

    CONSTRAINT uq_leave_types_name
        UNIQUE (name),

    CONSTRAINT chk_leave_types_days
        CHECK (default_days >= 0),

    CONSTRAINT chk_leave_types_active
        CHECK (is_active IN (0, 1))
);

CREATE TABLE leave_balances (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employee_id NUMBER NOT NULL,
    leave_type_id NUMBER NOT NULL,
    year NUMBER(4) NOT NULL,
    allocated_days NUMBER(5,2) DEFAULT 0 NOT NULL,
    used_days NUMBER(5,2) DEFAULT 0 NOT NULL,
    remaining_days NUMBER(5,2) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_leave_balances PRIMARY KEY (id),

    CONSTRAINT fk_leave_balances_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(id),

    CONSTRAINT fk_leave_balances_type
        FOREIGN KEY (leave_type_id)
        REFERENCES leave_types(id),

    CONSTRAINT uq_leave_balance
        UNIQUE (employee_id, leave_type_id, year),

    CONSTRAINT chk_leave_balance_allocated
        CHECK (allocated_days >= 0),

    CONSTRAINT chk_leave_balance_used
        CHECK (used_days >= 0),

    CONSTRAINT chk_leave_balance_remaining
        CHECK (remaining_days >= 0)
);

CREATE TABLE leave_requests (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employee_id NUMBER NOT NULL,
    leave_type_id NUMBER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    number_of_days NUMBER(5,2) NOT NULL,
    reason VARCHAR2(1000),
    status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,

    manager_approved_by NUMBER,
    manager_approved_at TIMESTAMP,

    hr_approved_by NUMBER,
    hr_approved_at TIMESTAMP,

    rejection_reason VARCHAR2(1000),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_leave_requests PRIMARY KEY (id),

    CONSTRAINT fk_leave_requests_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(id),

    CONSTRAINT fk_leave_requests_type
        FOREIGN KEY (leave_type_id)
        REFERENCES leave_types(id),

    CONSTRAINT fk_leave_requests_manager
        FOREIGN KEY (manager_approved_by)
        REFERENCES employees(id),

    CONSTRAINT fk_leave_requests_hr
        FOREIGN KEY (hr_approved_by)
        REFERENCES employees(id),

    CONSTRAINT chk_leave_request_dates
        CHECK (end_date >= start_date),

    CONSTRAINT chk_leave_request_days
        CHECK (number_of_days > 0),

    CONSTRAINT chk_leave_request_status
        CHECK (
            status IN (
                'PENDING',
                'MANAGER_APPROVED',
                'HR_APPROVED',
                'REJECTED',
                'CANCELLED'
            )
        )
);

CREATE TABLE payroll (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employee_id NUMBER NOT NULL,
    pay_period DATE NOT NULL,
    basic_salary NUMBER(12,2) DEFAULT 0 NOT NULL,
    allowances NUMBER(12,2) DEFAULT 0 NOT NULL,
    deductions NUMBER(12,2) DEFAULT 0 NOT NULL,
    gross_salary NUMBER(12,2) DEFAULT 0 NOT NULL,
    net_salary NUMBER(12,2) DEFAULT 0 NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    processed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_payroll PRIMARY KEY (id),

    CONSTRAINT fk_payroll_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(id),

    CONSTRAINT uq_payroll_employee_period
        UNIQUE (employee_id, pay_period),

    CONSTRAINT chk_payroll_basic_salary
        CHECK (basic_salary >= 0),

    CONSTRAINT chk_payroll_allowances
        CHECK (allowances >= 0),

    CONSTRAINT chk_payroll_deductions
        CHECK (deductions >= 0),

    CONSTRAINT chk_payroll_gross_salary
        CHECK (gross_salary >= 0),

    CONSTRAINT chk_payroll_net_salary
        CHECK (net_salary >= 0),

    CONSTRAINT chk_payroll_status
        CHECK (
            status IN (
                'PENDING',
                'PROCESSED',
                'FAILED'
            )
        )
);

CREATE TABLE performance_reviews (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employee_id NUMBER NOT NULL,
    reviewer_id NUMBER NOT NULL,
    review_period_start DATE NOT NULL,
    review_period_end DATE NOT NULL,
    rating NUMBER(2,1),
    comments CLOB,
    status VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    reviewed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_performance_reviews PRIMARY KEY (id),

    CONSTRAINT fk_performance_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(id),

    CONSTRAINT fk_performance_reviewer
        FOREIGN KEY (reviewer_id)
        REFERENCES employees(id),

    CONSTRAINT chk_performance_rating
        CHECK (rating IS NULL OR rating BETWEEN 1 AND 5),

    CONSTRAINT chk_performance_period
        CHECK (review_period_end >= review_period_start),

    CONSTRAINT chk_performance_status
        CHECK (
            status IN (
                'DRAFT',
                'SUBMITTED',
                'COMPLETED'
            )
        )
);

CREATE TABLE employee_goals (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employee_id NUMBER NOT NULL,
    title VARCHAR2(200) NOT NULL,
    description CLOB,
    target_date DATE,
    status VARCHAR2(20) DEFAULT 'NOT_STARTED' NOT NULL,
    progress_percentage NUMBER(5,2) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_employee_goals PRIMARY KEY (id),

    CONSTRAINT fk_employee_goals_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(id),

    CONSTRAINT chk_employee_goals_progress
        CHECK (progress_percentage BETWEEN 0 AND 100),

    CONSTRAINT chk_employee_goals_status
        CHECK (
            status IN (
                'NOT_STARTED',
                'IN_PROGRESS',
                'COMPLETED',
                'CANCELLED'
            )
        )
);

CREATE TABLE documents (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employee_id NUMBER NOT NULL,
    document_type VARCHAR2(50) NOT NULL,
    document_name VARCHAR2(200) NOT NULL,
    file_url VARCHAR2(500) NOT NULL,
    issue_date DATE,
    expiry_date DATE,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_documents PRIMARY KEY (id),

    CONSTRAINT fk_documents_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(id),

    CONSTRAINT chk_documents_status
        CHECK (
            status IN (
                'ACTIVE',
                'EXPIRED',
                'PENDING'
            )
        ),

    CONSTRAINT chk_documents_dates
        CHECK (
            expiry_date IS NULL
            OR issue_date IS NULL
            OR expiry_date >= issue_date
        )
);

CREATE TABLE notifications (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER NOT NULL,
    title VARCHAR2(200) NOT NULL,
    message VARCHAR2(1000) NOT NULL,
    notification_type VARCHAR2(30) NOT NULL,
    is_read NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    read_at TIMESTAMP,

    CONSTRAINT pk_notifications PRIMARY KEY (id),

    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id)
        REFERENCES users(id),

    CONSTRAINT chk_notifications_read
        CHECK (is_read IN (0, 1)),

    CONSTRAINT chk_notifications_type
        CHECK (
            notification_type IN (
                'LEAVE',
                'RECRUITMENT',
                'ONBOARDING',
                'PAYROLL',
                'PERFORMANCE',
                'DOCUMENT',
                'SYSTEM'
            )
        )
);

CREATE TABLE audit_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER,
    action VARCHAR2(50) NOT NULL,
    entity_type VARCHAR2(50) NOT NULL,
    entity_id NUMBER,
    old_value CLOB,
    new_value CLOB,
    ip_address VARCHAR2(45),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_audit_logs PRIMARY KEY (id),

    CONSTRAINT fk_audit_logs_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
);